spring:
  cloud:
    # Spring Cloud Gateway 配置项，对应 GatewayProperties 类
    gateway:
      # 路由配置项，对应 RouteDefinition 数组
      routes:
        ## accident-server 服务
        - id: accident-server-api # 路由的编号
          uri: grayLb://accident-server
          predicates: # 断言，作为路由的匹配条件，对应 RouteDefinition 数组
            - Path=/admin-api/accident-server/**
          filters:
              - RewritePath=/admin-api/accident-server/v3/api-docs?group=default, /v3/api-docs # 配置，保证转发到 /v3/api-docs
      x-forwarded:
        prefix-enabled: false # 避免 Swagger 重复带上额外的 /admin-api/accident 前缀

knife4j:
  # 聚合 Swagger 文档，参考 https://doc.xiaominfo.com/docs/action/springcloud-gateway 文档
  gateway:
    enabled: true
    routes:
      - name: 事故服务
        service-name: accident-server
        url: /admin-api/accident-server/v3/api-docs?group=default
        context-path: /
        order: 2